### ISSUE TITLE
Permission denied on OSC: Cannot run Euler example

### ISSUE THREAD

**Issue by guzman109** [ICICLE-ai/harp#6]
List of command I used.

`(base) [harp]$ module use $HOME/osc_apps/lmodfiles`
`(base) [harp]$ module load harp/1.1.0`
`(base) [harp]$ export CONDA_HOME=$HOME/miniconda3`
`(base) [harp]$ source $CONDA_HOME/bin/activate`
`(base) [harp]$ source activate harp_env`
`(harp_env) [01-eulers_number]$ chmod 755 *`
`(harp_env) [01-eulers_number]$ harp pipeline_config.json`
`bash: /users/<PROJECT>/<USERNAME>/osc_apps/harp/1.1.0/bin/harp: Permission denied`

**Comment by manikyaswathi** [comment]
Fix: Update the binaries with 755 before pushing to git.

**Comment by guzman109** [comment]
I logged back to OSC to try to test another run. I am getting permission issues again. Does this mean I have to do a fresh install everytime I want to use it?
